name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # 솔루션 파일이 있는 폴더 경로
  SOLUTION_FOLDER: CoMiExtractor/CoMiExtractor
  # 빌드 구성 (예: Release)
  BUILD_CONFIGURATION: Release
  # 빌드 플랫폼 (예: x86)
  BUILD_PLATFORM: x86

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      # 솔루션 폴더에서 명령 실행
      working-directory: ${{ env.SOLUTION_FOLDER }}
      run: msbuild CoMiExtractor.sln /t:Restore /p:Platform=${{env.BUILD_PLATFORM}}

    - name: Build
      # 솔루션 폴더에서 명령 실행
      working-directory: ${{ env.SOLUTION_FOLDER }}
      run: msbuild CoMiExtractor.sln /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} /p:OutDir=releases/${{env.BUILD_PLATFORM}}/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CoMiExtractor-${{env.BUILD_PLATFORM}}-binaries
        # 'working-directory'를 지원하지 않으므로, 리포지토리 루트 기준 전체 경로를 지정합니다.
        path: ${{ env.SOLUTION_FOLDER }}/releases/${{env.BUILD_PLATFORM}}/
