# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: CoMiExtractor/CoMiExtractor.sln

  # Configuration type to build (e.g., Release).
  BUILD_CONFIGURATION: Release

  # Platform to build for (e.g., x86, x64).
  # 이 부분을 'x64'로 변경하면 'releases/x64' 폴더에 빌드됩니다.
  BUILD_PLATFORM: x86

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # /p:OutDir 속성을 사용하여 빌드 결과물이 저장될 경로를 지정합니다.
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} /p:OutDir=releases/${{env.BUILD_PLATFORM}}/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CoMiExtractor-${{env.BUILD_PLATFORM}}-binaries
        # Set the working directory to the solution folder to match the build output location.
        working-directory: ${{ env.SOLUTION_ROOT }}
        # The path is now relative to the working directory.
        path: releases/${{env.BUILD_PLATFORM}}/
